{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# download pdf files automatically"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "start alarm signal.\n",
      "Time out!\n"
     ]
    }
   ],
   "source": [
    "import signal\n",
    "import time\n",
    " \n",
    "def set_timeout(num, callback):\n",
    "    def wrap(func):\n",
    "        def handle(signum, frame): \n",
    "            raise RuntimeError\n",
    " \n",
    "        def to_do(*args, **kwargs):\n",
    "            try:\n",
    "                signal.signal(signal.SIGALRM, handle) \n",
    "                signal.alarm(num) \n",
    "                print('start alarm signal.')\n",
    "                r = func(*args, **kwargs)\n",
    "                print('close alarm signal.')\n",
    "                signal.alarm(0)  \n",
    "                return r\n",
    "            except RuntimeError as e:\n",
    "                callback()\n",
    " \n",
    "        return to_do\n",
    " \n",
    "    return wrap\n",
    " \n",
    "def after_timeout():  \n",
    "    print(\"Time out!\")\n",
    "\n",
    "# example\n",
    "# @set_timeout(2, after_timeout) \n",
    "# def connect(): \n",
    "#     time.sleep(3)  \n",
    "#     print('Finished without timeout.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "\n",
    "@set_timeout(60*5, after_timeout)\n",
    "def download_pdf(save_path,pdf_name,pdf_url):\n",
    "    try:\n",
    "        print(\"downloading %s.pdf\" % (pdf_name))\n",
    "        r = requests.get(pdf_url, verify=False)\n",
    "        with open (save_path+pdf_name+\".pdf\", \"wb\") as code:\n",
    "            code.write(r.content)\n",
    "            print('%s.pdf download sucecssfully' % (pdf_name))\n",
    "    except Exception as e:\n",
    "        print(\"error downloading pdf from \" + pdf_url)    \n",
    "        print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import os\n",
    "# @set_timeout(60*5, after_timeout)\n",
    "# def download_pdf(save_path, pdf_name, pdf_url):\n",
    "#     os.system('wget {} -O {} --no-check-certificate'.format(pdf_url,save_path+pdf_name+\".pdf\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "with open(\"./s&p500.text\", \"r\") as f_obj:\n",
    "    for pdf_url in f_obj:\n",
    "        name = pdf_url.split(\"/\")[-1].split(\".pdf\")[0].replace(\"\\n\", \"\")\n",
    "        if not os.path.exists(\"./pdf_files/\"+name+\".pdf\"):\n",
    "            download_pdf(\"./pdf_files/\", name, pdf_url)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# delete invalid pdf files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import traceback\n",
    "from PyPDF2 import PdfFileReader\n",
    "\n",
    "def isValidPDF_pathfile(pathfile):\n",
    "    bValid = True\n",
    "    try:\n",
    "        # PdfFileReader(open(pathfile, 'rb'))\n",
    "        reader = PdfFileReader(pathfile)\n",
    "        if reader.getNumPages() < 1:\n",
    "            bValid = False\n",
    "    except:\n",
    "        bValid = False\n",
    "        print(pathfile + \" is invalid and will be removed!\")\n",
    "        # print(\"*\" + traceback.format_exc())\n",
    "\n",
    "    return bValid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<cq:s', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '\n",
      "<!D', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '\n",
      "<!DO', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!doc', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n",
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<html', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<html', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!doc', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '\n",
      "<!DO', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Xref table not zero-indexed. ID numbers for objects will be corrected.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n",
      "*Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_15339/3366981474.py\", line 8, in isValidPDF_pathfile\n",
      "    reader = PdfFileReader(pathfile)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1944, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 317, in __init__\n",
      "    self.read(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1374, in read\n",
      "    self._basic_validation(stream)\n",
      "  File \"/root/miniconda3/envs/camelotenv/lib/python3.10/site-packages/PyPDF2/_reader.py\", line 1420, in _basic_validation\n",
      "    raise PdfReadError(\n",
      "PyPDF2.errors.PdfReadError: PDF starts with '<!DOC', but '%PDF-' expected\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "\n",
    "input_path = \"./pdf_files\"\n",
    "pdf_files = os.listdir(input_path)\n",
    "for pdf_file in pdf_files:\n",
    "    path = os.path.join(input_path, pdf_file)\n",
    "    if not isValidPDF_pathfile(path):\n",
    "        os.remove(path)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.8 ('camelotenv')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "0223c632f617fca949c57c3ca0f5d1cb8bdc1aa423ed0406ba10b84d4d8863b4"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
